import { useEffect, useMemo, useRef, useState } from "react";
import { useNavigate, useParams, useSearchParams } from "react-router";
import { motion, AnimatePresence } from "motion/react";
import {
  BookOpen,
  CheckCircle2,
  Clock,
  Flame,
  X,
  XCircle,
} from "lucide-react";
import { useBoard } from "../context/BoardContext";
import { useConcepts } from "../context/ConceptContext";
import { useSessions } from "../context/SessionContext";
import {
  generateQuestions,
  recordRunFromSettings,
  type QuizAnswer,
  type QuizQuestion,
  type QuizScoredResult,
} from "../lib/api";
import { QUIZ_STYLE_OPTIONS, quizStyleLabel } from "../lib/quizStyles";
import { isLenientMatch, normalize } from "../lib/matching";
import type { Concept } from "../types";

type Phase = "question" | "revealed" | "done";

/** "3m 24s" / "45s" from seconds. */
function formatTime(seconds: number): string {
  const m = Math.floor(seconds / 60);
  const s = seconds % 60;
  return m > 0 ? `${m}m ${s}s` : `${s}s`;
}

/**
 * Quiz player. Questions are generated by the backend quiz engine from the
 * saved setting (style, tag filter, include-known), answered one at a time,
 * then recorded server-side on completion. Immediate right/wrong feedback is
 * computed locally against the board's concepts; the server re-scores
 * authoritatively when the run is saved.
 */
export function SessionPlay() {
  const { id } = useParams<{ id: string }>();
  const [searchParams] = useSearchParams();
  const boardId = id ?? "";
  const presetId = searchParams.get("presetId");

  // Keying the quiz by board + preset remounts it on navigation, which
  // re-initializes every piece of play state (index, answers, timer, results)
  // without resetting them in an effect.
  return <QuizSession key={`${boardId}:${presetId ?? "none"}`} boardId={boardId} presetId={presetId} />;
}

function QuizSession({ boardId, presetId }: { boardId: string; presetId: string | null }) {
  const navigate = useNavigate();

  const { boards } = useBoard();
  const { concepts, loadConcepts } = useConcepts();
  const { sessionPresets, loadSessionPresets, loadSessions } = useSessions();

  const board = boards.find((b) => b.id === boardId);
  const boardColor = board?.color ?? "#7c6af7";
  const preset = (sessionPresets[boardId] ?? []).find((p) => p.id === presetId);
  const style = preset?.style;

  const conceptById = useMemo(
    () => new Map((concepts[boardId] ?? []).map((c) => [c.id, c])),
    [concepts, boardId]
  );

  const [questions, setQuestions] = useState<QuizQuestion[] | null>(null);
  const [loadError, setLoadError] = useState<string | null>(null);
  const [index, setIndex] = useState(0);
  const [phase, setPhase] = useState<Phase>("question");
  const [elapsed, setElapsed] = useState(0);
  const [results, setResults] = useState<{ conceptId: string; correct: boolean }[]>([]);
  const [serverResults, setServerResults] = useState<QuizScoredResult[] | null>(null);
  const [selectedOption, setSelectedOption] = useState<string | null>(null);
  const [tfSelected, setTfSelected] = useState<boolean | null>(null);
  const [writtenInput, setWrittenInput] = useState("");
  const [inputVerdict, setInputVerdict] = useState<boolean | null>(null);
  const [quitting, setQuitting] = useState(false);
  const [submitError, setSubmitError] = useState<string | null>(null);

  const elapsedRef = useRef(0);
  const answersRef = useRef<QuizAnswer[]>([]);
  const savedRef = useRef(false);
  const advanceTimer = useRef<number | null>(null);

  const current = questions?.[index] ?? null;
  const total = questions?.length ?? 0;
  const progress = total > 0 ? index / total : 0;

  // Generate the session on entry: load domain data, resolve the preset, then
  // ask the backend for its questions. A 404 (no eligible concepts) or a
  // missing preset becomes the empty state.
  useEffect(() => {
    if (!boardId) return;
    let cancelled = false;

    (async () => {
      try {
        const [, loadedPresets] = await Promise.all([
          loadConcepts(boardId),
          loadSessionPresets(boardId),
        ]);
        if (cancelled) return;
        if (!presetId) {
          setQuestions([]);
          return;
        }
        const activePreset = loadedPresets.find((p) => p.id === presetId);
        if (!activePreset) {
          setQuestions([]);
          setLoadError("This saved setting no longer exists.");
          return;
        }
        const generated = await generateQuestions(boardId, {
          style: activePreset.style,
          tagIds: activePreset.tagIds ?? undefined,
          includeKnown: activePreset.includeKnown,
        });
        if (cancelled) return;
        setQuestions(generated);
      } catch (err) {
        if (cancelled) return;
        setQuestions([]);
        setLoadError(err instanceof Error ? err.message : "Failed to start session");
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [boardId, presetId, loadConcepts, loadSessionPresets]);

  // Elapsed timer — runs while a quiz is in progress.
  useEffect(() => {
    if (phase === "done" || total === 0) return;
    const timer = setInterval(() => {
      elapsedRef.current += 1;
      setElapsed(elapsedRef.current);
    }, 1000);
    return () => clearInterval(timer);
  }, [phase, total]);

  // Clear any pending auto-advance on unmount.
  useEffect(
    () => () => {
      if (advanceTimer.current) clearTimeout(advanceTimer.current);
    },
    []
  );

  async function saveRun() {
    if (savedRef.current || !boardId || !presetId) return;
    savedRef.current = true;
    if (answersRef.current.length === 0) return;
    try {
      const res = await recordRunFromSettings(boardId, presetId, {
        timeElapsedMs: elapsedRef.current * 1000,
        answers: answersRef.current,
      });
      setServerResults(res.results);
      await loadSessions(boardId);
    } catch (err) {
      setSubmitError(err instanceof Error ? err.message : "Failed to save this session");
    }
  }

  function scheduleAdvance(delayMs: number) {
    if (advanceTimer.current) clearTimeout(advanceTimer.current);
    advanceTimer.current = window.setTimeout(() => {
      advanceTimer.current = null;
      advance();
    }, delayMs);
  }

  function advance() {
    if (index + 1 >= total) {
      setPhase("done");
      void saveRun();
      return;
    }
    setSelectedOption(null);
    setTfSelected(null);
    setWrittenInput("");
    setInputVerdict(null);
    setPhase("question");
    setIndex((i) => i + 1);
  }

  function handleTFSelect(saysTrue: boolean) {
    if (phase !== "question" || !current || current.statement === undefined) return;
    const concept = conceptById.get(current.conceptId);
    const isTrue = normalize(current.statement) === normalize(concept?.answer ?? "");
    const correct = saysTrue === isTrue;
    setTfSelected(saysTrue);
    setPhase("revealed");
    answersRef.current.push({
      conceptId: current.conceptId,
      response: saysTrue,
      statement: current.statement,
    });
    setResults((prev) => [...prev, { conceptId: current.conceptId, correct }]);
    scheduleAdvance(1600);
  }

  function handleOptionSelect(option: string) {
    if (phase !== "question" || !current || current.options === undefined) return;
    const concept = conceptById.get(current.conceptId);
    const correct = normalize(option) === normalize(concept?.answer ?? "");
    setSelectedOption(option);
    setPhase("revealed");
    answersRef.current.push({ conceptId: current.conceptId, response: option });
    setResults((prev) => [...prev, { conceptId: current.conceptId, correct }]);
    scheduleAdvance(1400);
  }

  function handleCheckInput() {
    if (phase !== "question" || !current || !writtenInput.trim()) return;
    const concept = conceptById.get(current.conceptId);
    // Same lenient-matching rule the backend applies when it records the run.
    const correct = isLenientMatch(concept?.answer ?? "", writtenInput.trim());
    setInputVerdict(correct);
    setPhase("revealed");
    answersRef.current.push({ conceptId: current.conceptId, response: writtenInput.trim() });
    setResults((prev) => [...prev, { conceptId: current.conceptId, correct }]);
    scheduleAdvance(2400);
  }

  // The server's scored results win once the run is saved; until then the
  // locally-computed results drive the summary (they use the same rules).
  const effectiveResults: QuizScoredResult[] =
    serverResults ?? results.map((r) => ({ conceptId: r.conceptId, answeredCorrectly: r.correct }));
  const correctCount = effectiveResults.filter((r) => r.answeredCorrectly).length;
  const accuracy =
    effectiveResults.length > 0
      ? Math.round((correctCount / effectiveResults.length) * 100)
      : 0;
  const accuracyColor = accuracy >= 80 ? "#4ff0b8" : accuracy >= 50 ? "#f0c94f" : "#f07c4f";

  if (questions === null) {
    return (
      <main className="min-h-[70vh] flex items-center justify-center">
        <div className="w-8 h-8 rounded-full border-2 border-border border-t-primary animate-spin" />
      </main>
    );
  }

  if (total === 0) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[70vh] gap-6 text-center px-8">
        <BookOpen className="w-10 h-10 text-muted-foreground" />
        <div>
          <p className="text-foreground">
            {presetId ? "No concepts match this session setting" : "No session selected"}
          </p>
          <p className="text-sm text-muted-foreground mt-1 font-mono">
            {presetId
              ? "Try adjusting the tag filter or including learned concepts."
              : "Pick a saved setting on the board to start a session."}
          </p>
        </div>
        {loadError && <p className="text-xs text-rose-400 font-mono">{loadError}</p>}
        <button
          onClick={() => navigate(`/app/board/${boardId}`)}
          className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-primary text-primary-foreground text-sm hover:bg-primary/90 transition-colors"
        >
          Back to board
        </button>
      </div>
    );
  }

  // ── Done screen ────────────────────────────────────────────────────────────
  if (phase === "done") {
    return (
      <main className="max-w-lg mx-auto px-6 py-16 flex flex-col gap-8 items-center text-center">
        {submitError && <p className="text-xs text-rose-400 font-mono">{submitError}</p>}

        <motion.div
          initial={{ opacity: 0, scale: 0.9 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.4 }}
          className="flex flex-col items-center gap-2"
        >
          <div
            className="w-16 h-16 rounded-2xl flex items-center justify-center mb-2"
            style={{ background: `${accuracyColor}20` }}
          >
            {accuracy >= 80 ? (
              <CheckCircle2 className="w-8 h-8" style={{ color: accuracyColor }} />
            ) : accuracy >= 50 ? (
              <Flame className="w-8 h-8" style={{ color: accuracyColor }} />
            ) : (
              <XCircle className="w-8 h-8" style={{ color: accuracyColor }} />
            )}
          </div>
          <p className="text-xs text-muted-foreground tracking-widest uppercase font-mono">
            Session complete
          </p>
          <h1 className="text-foreground">{preset?.name ?? "Session"}</h1>
        </motion.div>

        <motion.div
          initial={{ opacity: 0, y: 12 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.1, duration: 0.35 }}
          className="w-full bg-card border border-border rounded-2xl p-6 flex flex-col gap-5"
        >
          <div className="flex flex-col gap-1.5">
            <div className="flex items-center justify-between">
              <span className="text-sm text-muted-foreground">Accuracy</span>
              <span className="font-mono" style={{ color: accuracyColor }}>
                {accuracy}%
              </span>
            </div>
            <div className="h-2.5 rounded-full bg-secondary overflow-hidden">
              <motion.div
                initial={{ width: 0 }}
                animate={{ width: `${accuracy}%` }}
                transition={{ duration: 0.8, ease: "easeOut", delay: 0.3 }}
                className="h-full rounded-full"
                style={{ background: accuracyColor }}
              />
            </div>
          </div>

          <div className="grid grid-cols-3 gap-3">
            {[
              { label: "Concepts", value: String(effectiveResults.length), color: boardColor },
              { label: "Correct", value: String(correctCount), color: "#4ff0b8" },
              { label: "Time", value: formatTime(elapsed), color: "#4fb8f0" },
            ].map((s) => (
              <div key={s.label} className="flex flex-col gap-1 bg-secondary rounded-xl px-3 py-2.5">
                <span className="text-[10px] uppercase tracking-widest text-muted-foreground font-mono">
                  {s.label}
                </span>
                <span className="font-mono text-sm" style={{ color: s.color }}>
                  {s.value}
                </span>
              </div>
            ))}
          </div>
        </motion.div>

        <motion.div
          initial={{ opacity: 0, y: 8 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.2, duration: 0.3 }}
          className="flex flex-col gap-3 w-full"
        >
          <button
            onClick={() => navigate(`/app/board/${boardId}/sessions`)}
            className="w-full py-3 rounded-xl bg-primary text-primary-foreground text-sm hover:bg-primary/90 transition-colors"
          >
            View session history
          </button>
          <button
            onClick={() => navigate(`/app/board/${boardId}`)}
            className="w-full py-3 rounded-xl border border-border text-muted-foreground text-sm hover:text-foreground hover:border-primary/30 transition-colors"
          >
            Back to board
          </button>
        </motion.div>
      </main>
    );
  }

  const concept = current ? conceptById.get(current.conceptId) : undefined;

  // ── Active session ─────────────────────────────────────────────────────────
  return (
    <main className="max-w-2xl mx-auto px-6 py-8 flex flex-col gap-6 min-h-[calc(100vh-4.5rem)]">
      {/* Top bar */}
      <div className="flex items-center gap-4">
        <button
          onClick={() => setQuitting(true)}
          className="text-muted-foreground hover:text-foreground transition-colors flex-shrink-0"
          aria-label="Quit session"
        >
          <X className="w-4 h-4" />
        </button>

        <div className="flex-1 h-1.5 rounded-full bg-secondary overflow-hidden">
          <motion.div
            className="h-full rounded-full"
            style={{ background: boardColor }}
            animate={{ width: `${progress * 100}%` }}
            transition={{ duration: 0.3, ease: "easeOut" }}
          />
        </div>

        <span className="text-xs font-mono text-muted-foreground flex-shrink-0">
          {index + 1} / {total}
        </span>

        <span className="text-xs font-mono text-muted-foreground flex items-center gap-1 flex-shrink-0">
          <Clock className="w-3 h-3" />
          {formatTime(elapsed)}
        </span>
      </div>

      {/* Question-type tag (display only) */}
      {style && (
        <span className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs bg-card border border-border text-foreground shadow-sm w-fit cursor-default select-none">
          {QUIZ_STYLE_OPTIONS.find((o) => o.id === style)?.icon}
          <span>{quizStyleLabel(style)}</span>
        </span>
      )}

      {/* Tags */}
      {concept && concept.tags.length > 0 && (
        <div className="flex flex-wrap gap-1.5">
          {concept.tags.map((tag) => (
            <span
              key={tag}
              className="text-[10px] px-2.5 py-1 rounded-full bg-secondary text-muted-foreground font-mono"
            >
              {tag}
            </span>
          ))}
        </div>
      )}

      {/* Question area */}
      <AnimatePresence mode="wait">
        <motion.div
          key={`${index}-${style}`}
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          exit={{ opacity: 0, y: -8 }}
          transition={{ duration: 0.22 }}
          className="flex flex-col gap-5 flex-1"
        >
          {style === "true_false" && current && current.statement !== undefined && (
            <TrueFalseMode
              concept={concept}
              statement={current.statement}
              phase={phase}
              selected={tfSelected}
              onSelect={handleTFSelect}
              boardColor={boardColor}
            />
          )}

          {style === "multiple_choice" && current && current.options !== undefined && (
            <MultipleChoiceMode
              concept={concept}
              options={current.options}
              phase={phase}
              selectedOption={selectedOption}
              onSelect={handleOptionSelect}
            />
          )}

          {style === "fill_in" && current && (
            <InputAnswerMode
              concept={concept}
              phase={phase}
              input={writtenInput}
              onInputChange={setWrittenInput}
              onCheck={handleCheckInput}
              verdict={inputVerdict}
            />
          )}
        </motion.div>
      </AnimatePresence>

      {/* Quit confirm */}
      <AnimatePresence>
        {quitting && (
          <div className="fixed inset-0 z-50 flex items-center justify-center px-4">
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="absolute inset-0 bg-black/60 backdrop-blur-sm"
              onClick={() => setQuitting(false)}
            />
            <motion.div
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.95 }}
              transition={{ duration: 0.18 }}
              className="relative bg-card border border-border rounded-2xl p-6 w-full max-w-sm flex flex-col gap-4 shadow-2xl shadow-black/50"
            >
              <h2 className="text-foreground">Quit session?</h2>
              <p className="text-sm text-muted-foreground">
                Progress won't be saved. You've reviewed {index} of {total} concepts.
              </p>
              <div className="flex gap-3">
                <button
                  onClick={() => navigate(`/app/board/${boardId}`)}
                  className="flex-1 py-2.5 rounded-xl border border-rose-500/30 text-rose-400 text-sm hover:bg-rose-500/10 transition-colors"
                >
                  Quit
                </button>
                <button
                  onClick={() => setQuitting(false)}
                  className="flex-1 py-2.5 rounded-xl bg-primary text-primary-foreground text-sm hover:bg-primary/90 transition-colors"
                >
                  Keep going
                </button>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </main>
  );
}

// ── True / False ───────────────────────────────────────────────────────────
function TrueFalseMode({
  concept,
  statement,
  phase,
  selected,
  onSelect,
  boardColor,
}: {
  concept: Concept | undefined;
  statement: string;
  phase: Phase;
  selected: boolean | null;
  onSelect: (value: boolean) => void;
  boardColor: string;
}) {
  const revealed = phase === "revealed";
  const isTrue = normalize(statement) === normalize(concept?.answer ?? "");
  const userCorrect = selected !== null && selected === isTrue;

  return (
    <div className="flex flex-col gap-5">
      <div className="bg-card border border-border rounded-2xl p-6 flex flex-col gap-1 relative overflow-hidden">
        <div className="absolute top-0 left-0 right-0 h-[3px]" style={{ background: boardColor }} />
        <span className="text-[10px] uppercase tracking-widest text-muted-foreground font-mono pt-1">
          Concept
        </span>
        <p className="text-xl text-foreground leading-snug mt-1" style={{ fontWeight: 500 }}>
          {concept?.title ?? "…"}
        </p>
      </div>

      <div
        className={`rounded-2xl border p-6 flex flex-col gap-2 transition-colors ${
          !revealed
            ? "bg-secondary border-border"
            : isTrue
              ? "bg-emerald-500/8 border-emerald-500/30"
              : "bg-rose-500/8 border-rose-500/30"
        }`}
      >
        <span className="text-[10px] uppercase tracking-widest font-mono text-muted-foreground">
          Is this statement true or false?
        </span>
        <p className="text-base text-foreground leading-relaxed">{statement}</p>

        {revealed && (
          <motion.p
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            className={`text-xs font-mono mt-1 ${isTrue ? "text-emerald-400" : "text-rose-400"}`}
          >
            {isTrue ? "This is the correct answer" : `Correct answer: ${concept?.answer}`}
          </motion.p>
        )}
      </div>

      {!revealed ? (
        <div className="grid grid-cols-2 gap-3">
          <button
            onClick={() => onSelect(false)}
            className="flex items-center justify-center gap-2 py-4 rounded-xl border border-rose-500/30 text-rose-400 hover:bg-rose-500/10 transition-colors text-sm"
          >
            <XCircle className="w-4 h-4" />
            False
          </button>
          <button
            onClick={() => onSelect(true)}
            className="flex items-center justify-center gap-2 py-4 rounded-xl border border-emerald-500/30 text-emerald-400 hover:bg-emerald-500/10 transition-colors text-sm"
          >
            <CheckCircle2 className="w-4 h-4" />
            True
          </button>
        </div>
      ) : (
        <motion.div
          initial={{ opacity: 0, y: 4 }}
          animate={{ opacity: 1, y: 0 }}
          className={`flex items-center justify-center gap-2 py-3.5 rounded-xl text-sm font-mono ${
            userCorrect
              ? "bg-emerald-500/10 text-emerald-400 border border-emerald-500/20"
              : "bg-rose-500/10 text-rose-400 border border-rose-500/20"
          }`}
        >
          {userCorrect ? (
            <>
              <CheckCircle2 className="w-4 h-4" /> Correct — moving on
            </>
          ) : (
            <>
              <XCircle className="w-4 h-4" /> Incorrect — moving on
            </>
          )}
        </motion.div>
      )}
    </div>
  );
}

// ── Multiple choice ────────────────────────────────────────────────────────
function MultipleChoiceMode({
  concept,
  options,
  phase,
  selectedOption,
  onSelect,
}: {
  concept: Concept | undefined;
  options: string[];
  phase: Phase;
  selectedOption: string | null;
  onSelect: (option: string) => void;
}) {
  const revealed = phase === "revealed";

  return (
    <div className="flex flex-col gap-5">
      <div className="bg-card border border-border rounded-2xl p-8">
        <span className="text-[10px] uppercase tracking-widest text-muted-foreground font-mono">
          Choose the correct answer
        </span>
        <p className="text-xl text-foreground leading-snug mt-2" style={{ fontWeight: 500 }}>
          {concept?.title ?? "…"}
        </p>
      </div>

      <div className="flex flex-col gap-2">
        {options.map((option, i) => {
          const isCorrect = normalize(option) === normalize(concept?.answer ?? "");
          const isSelected = option === selectedOption;

          let cls = "border-border text-foreground hover:border-primary/40 hover:bg-primary/5";
          if (revealed && isCorrect) cls = "border-emerald-500/50 bg-emerald-500/10 text-emerald-300";
          else if (revealed && isSelected && !isCorrect)
            cls = "border-rose-500/50 bg-rose-500/10 text-rose-300";
          else if (revealed) cls = "border-border text-muted-foreground opacity-40";

          return (
            <button
              key={i}
              onClick={() => onSelect(option)}
              disabled={revealed}
              className={`flex items-center gap-4 px-5 py-4 rounded-xl border text-sm text-left transition-all ${cls}`}
            >
              <span
                className={`w-6 h-6 rounded-full border flex-shrink-0 flex items-center justify-center text-[11px] font-mono transition-colors ${
                  revealed && isCorrect
                    ? "border-emerald-500 bg-emerald-500/20 text-emerald-400"
                    : revealed && isSelected
                      ? "border-rose-500 bg-rose-500/20 text-rose-400"
                      : "border-border text-muted-foreground"
                }`}
              >
                {revealed && isCorrect ? (
                  <CheckCircle2 className="w-3.5 h-3.5" />
                ) : revealed && isSelected ? (
                  <XCircle className="w-3.5 h-3.5" />
                ) : (
                  String.fromCharCode(65 + i)
                )}
              </span>
              {option}
            </button>
          );
        })}
      </div>

      {revealed && (
        <motion.p
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          className="text-xs text-muted-foreground font-mono text-center"
        >
          Next concept in a moment…
        </motion.p>
      )}
    </div>
  );
}

// ── Input answer ───────────────────────────────────────────────────────────
function InputAnswerMode({
  concept,
  phase,
  input,
  onInputChange,
  onCheck,
  verdict,
}: {
  concept: Concept | undefined;
  phase: Phase;
  input: string;
  onInputChange: (value: string) => void;
  onCheck: () => void;
  verdict: boolean | null;
}) {
  return (
    <div className="flex flex-col gap-5">
      <div className="bg-card border border-border rounded-2xl p-8">
        <span className="text-[10px] uppercase tracking-widest text-muted-foreground font-mono">
          Type your answer
        </span>
        <p className="text-xl text-foreground leading-snug mt-2" style={{ fontWeight: 500 }}>
          {concept?.title ?? "…"}
        </p>
      </div>

      {phase === "question" && (
        <div className="flex flex-col gap-3">
          <textarea
            value={input}
            onChange={(e) => onInputChange(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === "Enter" && !e.shiftKey && input.trim()) {
                e.preventDefault();
                onCheck();
              }
            }}
            placeholder="Write your answer here… (Enter to check)"
            rows={4}
            className="w-full px-4 py-3 rounded-xl bg-card border border-border text-sm text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-1 focus:ring-primary/50 resize-none transition-all"
            style={{ fontFamily: "var(--font-sans)" }}
          />
          <button
            onClick={onCheck}
            disabled={!input.trim()}
            className="self-end px-5 py-2.5 rounded-xl bg-primary text-primary-foreground text-sm hover:bg-primary/90 transition-colors disabled:opacity-40 disabled:cursor-not-allowed"
          >
            Check answer
          </button>
        </div>
      )}

      {phase === "revealed" && (
        <motion.div
          initial={{ opacity: 0, y: 8 }}
          animate={{ opacity: 1, y: 0 }}
          className="flex flex-col gap-4"
        >
          <div className="grid grid-cols-2 gap-3">
            <div className="flex flex-col gap-1.5 bg-card border border-border rounded-xl p-4">
              <span className="text-[10px] uppercase tracking-widest text-muted-foreground font-mono">
                Your answer
              </span>
              <p className="text-sm text-foreground leading-relaxed">
                {input.trim() || <span className="italic text-muted-foreground">No answer entered</span>}
              </p>
            </div>
            <div className="flex flex-col gap-1.5 bg-emerald-500/5 border border-emerald-500/25 rounded-xl p-4">
              <span className="text-[10px] uppercase tracking-widest text-emerald-400 font-mono">
                Correct answer
              </span>
              <p className="text-sm text-foreground leading-relaxed">{concept?.answer}</p>
            </div>
          </div>

          <motion.p
            initial={{ opacity: 0, y: 4 }}
            animate={{ opacity: 1, y: 0 }}
            className={`flex items-center justify-center gap-2 py-3.5 rounded-xl text-sm font-mono ${
              verdict
                ? "bg-emerald-500/10 text-emerald-400 border border-emerald-500/20"
                : "bg-rose-500/10 text-rose-400 border border-rose-500/20"
            }`}
          >
            {verdict ? (
              <>
                <CheckCircle2 className="w-4 h-4" /> Correct — moving on
              </>
            ) : (
              <>
                <XCircle className="w-4 h-4" /> Incorrect — moving on
              </>
            )}
          </motion.p>
        </motion.div>
      )}
    </div>
  );
}
